### PR TITLE
Dursi blog

### PR DESCRIPTION
**Pull request by ljdursi**
This is also on the US-RSE blog aggregator, but there is a lot of HPC-related content...

### CODE REVIEW

**Comment by vsoch** [comment]
Woot! Would you mind running the script locally as a sanity check that the posts import OK?

**Comment by ljdursi** [comment]
Ah, sorry, looks good:

```
(blog) ljdursi@MacBook-Pro blog-1 % python scripts/generate_posts.py _data/authors.yml --output _posts/ --test
[TEST] new author folder /Users/ljdursi/tmp/blog-1/_posts/dursi
Preparing new post: /Users/ljdursi/tmp/blog-1/_posts/dursi/2022-7-3-utility-vs-professional-serviecs.html.md
Preparing new post: /Users/ljdursi/tmp/blog-1/_posts/dursi/2022-2-26-1500-jobs.html.md
...
Preparing new post: /Users/ljdursi/tmp/blog-1/_posts/dursi/2010-6-17-codes-as-instruments-community-applications-and-simulation-software-for-the-hardware-architectures-of-the-next-decade.html.md
Preparing new post: /Users/ljdursi/tmp/blog-1/_posts/dursi/2010-5-1-canadian-astronomical-computing-data-netowork-facilities.html.md
```

And after running it for real, things looked good on a spot-check of a few of the posts.

In general, would you want the posts as part of the PR?

**Comment by vsoch** [comment]
Yes let's add them! It doesn't hurt if you generated them already!

**Comment by vsoch** [comment]
But actually, we can just merge and I can manually trigger - so this works! Thank you @ljdursi !

**Review by vsoch — APPROVED** [review]

**Pull request merged**
