### PR TITLE
Add CaRCC to hpc.social

### PR DESCRIPTION
**Pull request by middelkoopt**
Please consider adding CaRCC to hpc.social.

### CODE REVIEW

**Comment by vsoch** [comment]
Taking a look!

**Comment by vsoch** [comment]
Are these posts of a particular type or tag? E.g., I'm seeing some that are article-like, others more event announcements. Is there perhaps a filter (category or label) we want to choose for the blog?

**Comment by middelkoopt** [comment]
What types of posts/materials are appropriate for syndication on hpc.social?  The CaRCC posts are pretty low volume and are generally around the "community announcement" theme with an intent to start posting more original content (for example https://carcc.org/2022/10/03/understanding-the-carcc-facings/).

**Comment by vsoch** [comment]
That's a good question! I think my original bias was more personal blog articles, but let's have a quick discussion - pinging @alansill @FCLC.

I think my concern is keeping the blog to be posts with opinions written by people, and not a place that gets muddled by event postings, etc. Possibly we need a different place for those kinds of feeds - something that also is posted to different social media places (slack / Twitter / Mastodon) - akin to a jobs job? But this is my opinion and it might be wrong. My quick thinking is if maybe there are a subset of posts in here that maybe we could identify with a category / tag (which something like wordpress can do) we might better filter the content with that.

Let me know your thoughts!

**Comment by FCLC** [comment]
Taking a look now :blush:

**Comment by FCLC** [comment]
Initial thinking is inline with @vsoch; if we're going to be adding/hosting content for people in HPC and around, by people in and around HPC, it should probably be blog style content. 

IMO content that comes to mind is short mussing, personal explorations, technical deep dives, personal projects (#homelab content?), some educational tutorial content (this one I want to be careful with due to affiliation with vendors. I'm not against a post from say Xilinx on how an FPGA can be deployed within a node to build a special, fit for purpose accelerator, but I don't want it to smell like a sales pitch either...)

As for tagging, that's a functionality that we should be looking at. From the example above, long technical deep dives on software should probably be marked differently than a short, humorous ~~rant~~ post on the "meme du jour" (Exascale, Moore's Law etc. )

If that's only a tag at the bottom, a different colour code etc. I'm not sure (UX is *hard*). As Vsoch said, Wordpress amongst other platforms already has tags, so we can use those on import to get a decent fit for categories and linking those to the UX in accessible ways. 

For sharing different events from different centers, orgs etc. (including CaRCC) I'm not certain.

Off the cuff I can picture something like this:

A community calendar hosted somewhere on the main site, where various orgs can submit/send calendar invites to something like "events@hpc.social". Something as simple as a bash script+cronjob scrapes the `cal.ics` and adds to a central calendar marked as UTC for timecode. That calendar is marked as open and users can subscribe to it. Those interested can import/watch the "HPC.social" calendar if they want all events in their feed, or just look at the site to see what's coming up? 

Easy to mute, avoids sharing user data with 1001 vendors, provides a service to the community etc. (I wasn't the one to set it up, but my engineering society back in Uni did something similar to avoid/centralize the colossal amount of BS emails different execs were getting for speakers/event planners etc. Made our inboxes *much* cleaner)


Assuming the calendar invite comes with the event announcement information/link to the host site itself that should be fine? Most mailing list services for events have calendar invite functionality, so it's not extra load onto those wanting to work with hpc.social for event sharing

**Comment by vsoch** [comment]
I think we are in agreement! So to summarize:

- blog is for more article-like things (and we could extend this with tags / topics or some other organization)
- we have a missing resource we need for feeds / resources related to events (and an easy way to submit).

@MiddelkoopT - let's figure out the best way to add CaRCC. I'm thinking that since you are using Wordpress, if someone is able to create categories for the posts (e.g., community-call, news, article) then we can generate a tag specific feed for the blog site here (e.g., for the articles - an example here - https://carcc.org/2022/05/25/2021-rcd-capabilities-model-community-data-report-now-available/). And your site actually already has support for this, actually! E.g., here is a feed https://carcc.org/category/rcd-nexus/feed/ for the "nexus" category. So it would just mean someone going in and adding some extra category tags.

Then we can add that category tag feed here. And I think we do need a way for the CaRCC to share events  or shoutout to look at a community call - @FCLC should we make a new Discussion item with the content that you have above plus a link to CaRCC as an example?

**Comment by middelkoopt** [comment]
We were thinking along similar lines of having a dedicated tag for hpc.social content.

For content, does the following articles fall into what we are looking for?
* https://carcc.org/2022/10/03/understanding-the-carcc-facings/
* https://carcc.org/2022/05/25/2021-rcd-capabilities-model-community-data-report-now-available/

If that's good I'll tag the articles and update the branch and push the update and notify.

**Comment by vsoch** [comment]
@MiddelkoopT yes! Those are exactly the two that stuck out to me to fit to include here as well.

**Comment by middelkoopt** [comment]
Tag implemented on CaRCC side and update pushed.  Ready for publication.

**Review by vsoch — APPROVED** [review]

**Comment by middelkoopt** [comment]
Thanks!

**Comment by FCLC** [comment]
> I think we are in agreement! So to summarize:
> 
>     * blog is for more article-like things (and we could extend this with tags / topics or some other organization)
> 
>     * we have a missing resource we need for feeds / resources related to events (and an easy way to submit).
> 
> 
> @MiddelkoopT - let's figure out the best way to add CaRCC. I'm thinking that since you are using Wordpress, if someone is able to create categories for the posts (e.g., community-call, news, article) then we can generate a tag specific feed for the blog site here (e.g., for the articles - an example here - https://carcc.org/2022/05/25/2021-rcd-capabilities-model-community-data-report-now-available/). And your site actually already has support for this, actually! E.g., here is a feed https://carcc.org/category/rcd-nexus/feed/ for the "nexus" category. So it would just mean someone going in and adding some extra category tags.
> 
> Then we can add that category tag feed here. And I think we do need a way for the CaRCC to share events or shoutout to look at a community call - @FCLC should we make a new Discussion item with the content that you have above plus a link to CaRCC as an example?

Will do :blush:

**Comment by FCLC** [comment]
Discussion: https://github.com/hpc-social/hpc-social.github.io/discussions/51

**Comment by vsoch** [comment]
hey @MiddelkoopT I wanted to let you know we are doing some organizing, and placed CaRCC in the bucket of community projects: https://hpc.social/community-blog/. The original site here now is a portal to these new spaces!  https://hpc.social/blog/. We are hoping this makes the blog space we host more inclusive for different kinds of blogs - the current one was strongly "personal blogs" and I suspect some orgs would feel they didn't belong.

It's a fairly simple setup for the time being, but we will improve upon it. I wanted to double check this is OK with you, and if not we can talk about what you'd like instead. Thank you!

**Comment by middelkoopt** [comment]
Sounds good for now. Tim.

--
Sent from my mobile device.
________________________________

**Pull request merged**
