### PR TITLE
Add Thinking Out Loud (Adam DeConinck's blog)

### PR DESCRIPTION
**Pull request by ajdecon**
Pointing to the `Computing` category feed on my Wordpress blog, so that the shared blog doesn't get every random thought. 😄 

```
% python scripts/generate_posts.py _data/authors.yml --output _posts/ --test
[TEST] new author folder /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-11-27-p=264.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-11-1-p=247.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-10-30-p=235.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-5-14-p=227.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-3-12-p=13.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-2-25-p=203.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-2-12-p=167.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2022-1-15-p=176.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2021-1-2-p=147.md
Preparing new post: /Users/ajdecon/src/blog-hpc-social/_posts/thinking-ajdecon-org/2020-12-14-p=113.md
```

### CODE REVIEW

**Comment by vsoch** [comment]
Do the pages render OK with the `p=176` ? Since that's the identifier it's probably ok to keep, I just want to make sure it looks okay to render.

**Comment by vsoch** [comment]
@ajdecon I'm going to test this locally and get it online asap! After seeing the wonky permalinks I did some tweaks to fix it.

**Comment by vsoch** [comment]
Okay you are added! Sorry for being slow on this - and I figured it would be faster to push than make you rebase, etc.

image

Thank you for the contributions today! :partying_face:

**Comment by ajdecon** [comment]
Thank you for getting this fixed! And apologies for the lack of reply last night, I ended up occupied with a needy puppy. 🐶

**Comment by vsoch** [comment]
Ah totally understandable! :dog:

**Pull request closed without merging**
